[package]
name = "robogen-topopt"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
faer = { version = "=0.22.6", default-features = false, features = ["std", "sparse-linalg"] }
robogen-domain = { path = "../robogen-domain" }
robogen-ir = { path = "../robogen-ir" }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

